#!/usr/bin/env python

"""
Wrapper program to run ro command line utility
"""

import sys
import os
import os.path
import logging
logging.basicConfig()

progdir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, progdir) # Insert at front of path to override pre-installed rdflib, if any

from checklist import mkminim

configbase = os.path.expanduser("~")
filebase   = os.getcwd()
status     = mkminim.runCommand(configbase, filebase, sys.argv)
sys.exit(status)

# End.
