#!/usr/bin/env python
"""
mkminim

Wrapper program to run sptreadsheet-to-Minim converter utility
"""
__author__      = "Graham Klyne (GK@ACM.ORG)"
__copyright__   = "Copyright 2011-2013, University of Oxford"
__license__     = "MIT (http://opensource.org/licenses/MIT)"

import sys
import os
import os.path
import logging
logging.basicConfig()

progdir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, progdir) # Insert at front of path to override pre-installed rdflib, if any

from checklist import mkminim

configbase = os.path.expanduser("~")
filebase   = os.getcwd()
status     = mkminim.runCommand(configbase, filebase, sys.argv)
sys.exit(status)

# End.
