#!/usr/bin/env python
"""
ro

Wrapper program to run RO Manager command line utility
"""
__author__      = "Graham Klyne (GK@ACM.ORG)"
__copyright__   = "Copyright 2011-2013, University of Oxford"
__license__     = "MIT (http://opensource.org/licenses/MIT)"

import sys
import os
import os.path
import logging
logging.basicConfig()

progdir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, progdir) # Insert at front of path to override pre-installed rdflib, if any

from rocommand import ro

configbase = os.path.expanduser("~")
robase = os.getcwd()
status = ro.runCommand(configbase, robase, sys.argv)
sys.exit(status)

# End.
