#!/usr/bin/env python

"""
Wrapper program to run ro command line utility
"""

import sys
import os
import os.path

progdir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, progdir) # Insert at front of path to override pre-installed rdflib, if any

from rocommand import ro

configbase = os.path.expanduser("~")
robase = os.getcwd()
status = ro.runCommand(configbase, robase, sys.argv)
sys.exit(status)

# End.
